### PR TITLE
docs: update readme to reflect change presented in AP-137

### PR DESCRIPTION
**Pull request by jeansimon**
This updates the README to reflect changes presented in https://github.com/zapier/zapier/pull/46039. We're now exposing the `subscribeData` in `perform` _and_ `performUnsubscribe`.  

Related [JIRA Ticket](https://zapierorg.atlassian.net/browse/AP-137)

Are there any other pieces of documentation that I missed and should be updated?

### CODE REVIEW

**Review by xavdid — APPROVED** [review]
awesome! this has been a long time feature request: https://github.com/zapier/zapier-platform/issues/12.

If it's live now, we can close that out!

**Review by xavdid — CHANGES_REQUESTED** [review]
ah wait, sorry - I just saw you edited `README.md`

You instead need to edit `README-source.md` and run the `yarn docs` command. I can run the command for you if you don't have this repo set up locally.

**Review by xavdid — APPROVED** [review]
perfect! thank you!

**Comment by jeansimon** [comment]
@xavdid and to answer your other question, yes, this change is already live :)

**Pull request merged**
