### PR TITLE
SUPPORTESC-163 docs(cli): Update historical releases section to include v10

### PR DESCRIPTION
**Pull request by nicolemichellethomas**
Starting Draft pull request to update docs with links to v10.2.0, now that they are on v11

### CODE REVIEW

**Comment by xavdid** [comment]
Thanks for this contribution @nicolemichellethomas. The only trick is that you'll need to make changes in the `README-source.md` file instead of `README`. Then, when you commit (if you're run `yarn` recently), the new docs will auto-build.

Let me know if that doesn't make sense!

**Review by eliangcs — APPROVED** [review]
I pushed a commit that makes the change on `README-source.md` and regenerates the docs. Thanks!

**Comment by nicolemichellethomas** [comment]
Oh sorry folks! Thanks for the information, and the assist!

**Comment by xavdid** [comment]
No problem at all! It's a confusing setup. I figured you'd continue to make readme updates, so now you know! :)

**Pull request merged**
