### PR TITLE
[SUPPORTESC-179] docs(cli): Add information about header format in bundle.rawRequest

### PR DESCRIPTION
**Pull request by armchairlinguist**
Adds a note about how headers are (re)formatted in the bundle, so that devs no longer need to guess/test.
Relevant to #290 - we may improve this in the future, in which case this addition would need to be removed.

### CODE REVIEW

**Comment by armchairlinguist** [comment]
My testing on this indicated that headers are not typically available in `bundle.cleanedRequest`, even though [Line 888](https://github.com/zapier/zapier-platform/pull/401/files#diff-3dde54695dbc62f7d2d2212cc889a7aeb3fbffee64355037ceaaba6755b616afR888) suggests that they may be. Is my testing missing something, or can we say that they are not present?

**Review by codebycaleb — CHANGES_REQUESTED** [review]
The content looks great! Can you run `yarn run docs` from inside `packages/cli/` to generate the rest of the README docs? Then I'll be happy to give the 👍

**Comment by armchairlinguist** [comment]
Oh of course, sorry! I got lazy and did this in the UI, and forgot that step.

**Review by codebycaleb — DISMISSED** [review]

**Comment by armchairlinguist** [comment]
Just to add context, the situation with cleanedRequest is more complex per recent discussions, so I'm going to merge this PR as-is, and any changes there can be separate.

**Review by codebycaleb — APPROVED** [review]

**Pull request merged**
