### PR TITLE
PDE-2218  Bump cli, core, schema 11.1.1 -> 11.2.0

### PR DESCRIPTION
**Pull request by bryanhelmig**
To catch the new, backwards compatible changes around dynamic key (which is getting backported to 9.x too).

https://github.com/zapier/zapier-platform/pull/455 https://github.com/zapier/zapier-platform/pull/432 https://github.com/zapier/zapier-platform/pull/408

### CODE REVIEW

**Comment by xavdid** [comment]
nice! this looks good, but we'll probably want to include https://github.com/zapier/zapier-platform/pull/454 before we cut the release.

**Comment by bryanhelmig** [comment]
Cool, thats a good idea @xavdid!

**Comment by bryanhelmig** [comment]
I think @eliangcs had planned on cutting a few releases (including the backport), so I'll let him do that tonight/tomorrow.

**Comment by eliangcs** [comment]
@bryanhelmig I'd like to ship another [bug fix](https://zapierorg.atlassian.net/browse/PDE-2826) in the new release. So can we hold off the release if possible?

**Comment by bryanhelmig** [comment]
@eliangcs absolutely, no rush.

**Review by eliangcs — APPROVED** [review]

**Pull request merged**
