### PR TITLE
fix(legacy-scripting-runner): backport #475; handle empty scripting string

### PR DESCRIPTION
**Pull request by xavdid**
see #475

### CODE REVIEW

**Comment by xavdid** [comment]
I don't think it's urgent, but can you handle releasing this?

**Review by eliangcs — APPROVED** [review]
@xavdid thanks! I can handle the release. But I'd like to ship the logging improvement, which I'm currently working on, in the next release, so we'll have to wait. I hope that's ok.

**Comment by xavdid** [comment]
Sure, no problem! And just to double check, we _do_ merge this? I remember we were not merging backports for a while and just basing releases off branches, but it seems like using `release-9.x` changes that

**Comment by eliangcs** [comment]
@xavdid yes, we want to merge this to `release-9.x`. We used to not have a branch but it was hard to track what's going on with 9.x. Having a `release-9.x` branch is makes it easier.

I'll merge this. Thanks!

**Pull request merged**
