### PR TITLE
docs(schema): Clarify FieldSchema.list for input v output fields

### PR DESCRIPTION
**Pull request by shalgrim**
You wouldn't know for sure from reading the original description what this meant for output fields, so I wanted to be more explicit about it

### CODE REVIEW

**Comment by shalgrim** [comment]
finally coming back to this...`yarn docs` gives me an error...not a clear one either. i'll look into this but thought it might be faster to ask here too:

```
➜  schema git:(clarify-FieldSchema-list) ✗ yarn docs
yarn run v1.21.1
$ node bin/docs.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'jsonschema'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/scott/zapier-platform/packages/schema/lib/utils/makeValidator.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  schema git:(clarify-FieldSchema-list) ✗ pwd
/Users/scott/zapier-platform/packages/schema
```

**Comment by xavdid** [comment]
did you run `yarn` before running `yarn docs`? You'd think that commands would make sure that the installed modules are fresh, but they don't

**Comment by shalgrim** [comment]
That did it, thanks! Right before I saw your message I was about to run `npm install`. Would that have fixed it, too?

**Comment by xavdid** [comment]
that would have probably worked, but `npm` installs things a little differently (aka makes different guarantees) than `yarn`, so the latter is preferred.

**Pull request merged**
