### PR TITLE
Add re-encrypted credentials for s3 publish

### PR DESCRIPTION
**Pull request by zrochler**

### CODE REVIEW

**Comment by xavdid** [comment]
looks like the tests failed because the new value wasn't parsed correctly. once that's working correctly, this should be good to go.

**Comment by zrochler** [comment]
@xavdid it looks like smoke tests are failing, but I have no idea if that's related to this change.

**Comment by eliangcs** [comment]
The tests are failing because https://auth-json-server.zapier.ninja is shut down. Will need to switch to the new host once it's ready.

**Comment by eliangcs** [comment]
Tests are passing now. Merging.

**Pull request merged**
