### PR TITLE
PDE-2085 chore: bump node-fetch to 2.6.6

### PR DESCRIPTION
**Pull request by eliangcs**
Same as #458 but for 11.x.

### CODE REVIEW

**Review by xavdid — APPROVED** [review]
cool. Is there a reason for the bump, or just staying current? Do we anticipate any issues in legacy-script runner on the 9.x branch?

**Comment by eliangcs** [comment]
@xavdid thanks for asking! I wrote the reason in the description of https://github.com/zapier/zapier-platform/pull/458.

**Comment by xavdid** [comment]
wow those checks were so fast 😅

**Comment by eliangcs** [comment]
> wow those checks were so fast 

Exactly! We should've moved away from Travis earlier. I don't know why, but the latency between GitHub Actions and our test servers (https://httpbin.zapier-tooling.com and https://auth-json-server.zapier-staging.com) is super short!

**Pull request merged**
